use serde::{Deserialize, Serialize};

/// Represents Motivation as a finite fuel source.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Coal {
    pub amount: f32,
    pub quality: f32, // 0.0 to 1.0, representing the purity of motivation
}

/// Represents Progress generated by burning Coal.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Steam {
    pub pressure: f32,
    pub velocity: f32,
}

/// Represents Intrinsic Load (the concept being taught).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Cargo {
    pub name: String,
    pub weight: f32, // Represents the Intrinsic Load value
    pub description: String,
}
